version: '3' # docker version
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html" # sync project dir with container web dir
    ports:
      - 8080:80
      - 443:443 # for future ssl traffic
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=eg-pps
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test # this should live in .env file
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    ports:
      - 3306:3306
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      # mount a volume for mysql to not lose db data
      - ./volumes/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/structure.sql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=100M
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db

  composer:
    image: composer:2.7
    volumes:
      - "./src:/var/www/html"
    working_dir: /var/www/html
    command: install
